version: '3.8'

services:
  auth:
    container_name: "auth"
    restart: unless-stopped
    volumes:
      - .:/go/src/github.com/escalopa/goauth/
    environment:
      - AUTH_GRPC_PORT=${AUTH_GRPC_PORT}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - TOKEN_ACCESS_DURATION=${TOKEN_ACCESS_DURATION}
      - CACHE_URL=${CACHE_URL}
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    build:
      context: .
      dockerfile: ./_deployments/Dockerfile.auth
      target: development

  email:
    container_name: "email"
    restart: unless-stopped
    volumes:
      - .:/go/src/github.com/escalopa/contact/
    environment:
      - EMAIL_GRPC_PORT=${EMAIL_GRPC_PORT}
      - MIN_SEND_INTERVAL=${MIN_SEND_INTERVAL}
      - COURIER_TOKEN=${COURIER_TOKEN}
      - COURIER_VERIFICATION_TEMPLATE_ID=${COURIER_VERIFICATION_TEMPLATE_ID}
    ports:
      - "${EMAIL_GRPC_PORT}:${EMAIL_GRPC_PORT}"
    build:
      context: .
      dockerfile: _deployments/Dockerfile.contact
      target: development

  cache:
    image: redis:alpine
    container_name: "cache"
    restart: unless-stopped
    volumes:
      - ./storage/cache:/data
    ports:
      - "6379:6379"

