version: '3.8'

services:
  auth:
    container_name: "auth"
    restart: unless-stopped
    volumes:
      - .:/go/src/github.com/escalopa/auth/
    environment:
      - AUTH_CACHE_URL=${AUTH_CACHE_URL}
      - AUTH_GRPC_PORT=${AUTH_GRPC_PORT}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - TOKEN_ACCESS_DURATION=${TOKEN_ACCESS_DURATION}
      - EMAIL_GRPC_URL=${EMAIL_GRPC_URL}
    ports:
      - "${AUTH_GRPC_PORT}:${AUTH_GRPC_PORT}"
    build:
      context: .
      dockerfile: ./_deployments/Dockerfile.auth
      target: development
    depends_on:
      - cache
      - email

  email:
    container_name: "email"
    restart: unless-stopped
    volumes:
      - .:/go/src/github.com/escalopa/contact/
    environment:
      - EMAIL_CACHE_URL=${EMAIL_CACHE_URL}
      - EMAIL_GRPC_PORT=${EMAIL_GRPC_PORT}
      - CODE_LENGTH=${CODE_LENGTH}
      - CODE_EXPIRATION=${CODE_EXPIRATION}
      - MIN_SEND_INTERVAL=${MIN_SEND_INTERVAL}
      - COURIER_TOKEN=${COURIER_TOKEN}
      - COURIER_VERIFICATION_TEMPLATE_ID=${COURIER_VERIFICATION_TEMPLATE_ID}
    ports:
      - "${EMAIL_GRPC_PORT}:${EMAIL_GRPC_PORT}"
    build:
      context: .
      dockerfile: _deployments/Dockerfile.contact
      target: development
    depends_on:
        - cache

  cache:
    image: redis:alpine
    container_name: "cache"
    restart: unless-stopped
    volumes:
      - ./storage/cache:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
