version: "3.8"

services:
  auth:
    container_name: "auth"
    restart: unless-stopped
    volumes:
      - ./auth:/go/src/github.com/escalopa/fingo/auth
      - ./pb:/go/src/github.com/escalopa/fingo/pb
      - ./pkg:/go/src/github.com/escalopa/fingo/pkg
      - ./certs:/go/src/github.com/escalopa/fingo/certs
    env_file: ./auth/app.env
    ports:
      - "${AUTH_GRPC_PORT}:${AUTH_GRPC_PORT}"
    build:
      context: .
      dockerfile: ./_deployments/Dockerfile.auth
      target: development
    depends_on:
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      token:
        condition: service_started
      jaeger:
        condition: service_started

  wallet:
    container_name: "wallet"
    restart: unless-stopped
    volumes:
      - ./wallet:/go/src/github.com/escalopa/fingo/wallet
      - ./pb:/go/src/github.com/escalopa/fingo/pb
      - ./pkg:/go/src/github.com/escalopa/fingo/pkg
      - ./certs:/go/src/github.com/escalopa/fingo/certs
    env_file: ./wallet/app.env
    ports:
      - "${WALLET_GRPC_PORT}:${WALLET_GRPC_PORT}"
    build:
      context: .
      dockerfile: ./_deployments/Dockerfile.wallet
      target: development
    depends_on:
      token:
        condition: service_started
      crdb:
        condition: service_healthy

  token:
    container_name: "token"
    restart: unless-stopped
    volumes:
      - ./token:/go/src/github.com/escalopa/fingo/token
      - ./pb:/go/src/github.com/escalopa/fingo/pb
      - ./pkg:/go/src/github.com/escalopa/fingo/pkg
      - ./certs:/go/src/github.com/escalopa/fingo/certs
    env_file: ./token/app.env
    build:
      context: .
      dockerfile: ./_deployments/Dockerfile.token
      target: development
    ports:
      - "${TOKEN_GRPC_PORT}:${TOKEN_GRPC_PORT}"
    depends_on:
      cache:
        condition: service_healthy
      jaeger:
        condition: service_started

  contact:
    container_name: "contact"
    restart: unless-stopped
    volumes:
      - ./contact:/go/src/github.com/escalopa/fingo/contact
      - ./pb:/go/src/github.com/escalopa/fingo/pb
      - ./pkg:/go/src/github.com/escalopa/fingo/pkg
      - ./certs:/go/src/github.com/escalopa/fingo/certs
    env_file: ./contact/app.env
    build:
      context: .
      dockerfile: _deployments/Dockerfile.contact
      target: development
    depends_on:
      rabbitmq:
        condition: service_healthy
      jaeger:
        condition: service_started

  cache:
    image: redis:alpine
    container_name: "cache"
    restart: unless-stopped
    volumes:
      - cache:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 2s
      timeout: 2s
      retries: 5

  db:
    image: postgres:12
    container_name: "db"
    env_file: ./.db.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./scripts/multiple-database.sh:/docker-entrypoint-initdb.d/multiple-database.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 5

  crdb: # Master node
    image: cockroachdb/cockroach:latest
    container_name: "crdb"
    volumes:
      - crdb:/cockroach/cockroach-data
      - ./scripts/cockroach-inti.sh:/cockroach-inti.sh
    entrypoint: ["/bin/bash"]
    command: ["/cockroach-inti.sh"]
    ports:
      - "26257:26257"
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "cockroach", "node", "status", "--insecure" ]
      interval: 2s
      timeout: 2s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.10.19-management
    container_name: "rabbitmq"
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia/'

    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: ./.rabbitmq.env
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 3s
      timeout: 5s
      retries: 5

  jaeger:
    container_name: "jaeger"
    restart: unless-stopped
    image: jaegertracing/all-in-one:1.6
    ports:
      - "16686:16686"
      - "14268:14268"
      - "4318:4318"
      - "6831:6831/udp"

volumes:
  crdb:
  rabbitmq:
  cache:
  db:
