version: "3.8"

services:
  auth:
    image: dekuyo/fingo_auth:latest
    environment:
      - AUTH_GRPC_PORT=9002
      - TOKEN_GRPC_URL=token:9001
      ## TRACING
      - AUTH_TRACING_ENABLE=true
      - AUTH_TRACING_JAEGER_ENABLE=true
      - AUTH_TRACING_JAEGER_AGENT_URL=http://jaeger:14268/api/traces
      - AUTH_TRACING_JAEGER_SERVICE_NAME=auth
      - AUTH_TRACING_JAEGER_ENVIRONMENT=development
      ## TLS CERTIFICATES
      - AUTH_GRPC_TLS_ENABLE=true
      - AUTH_GRPC_TLS_CERT_FILE=/certs/server-cert.pem
      - AUTH_GRPC_TLS_KEY_FILE=/certs/server-key.pem
      ## TOKEN TLS CERTIFICATES
      - TOKEN_GRPC_TLS_ENABLE=true
      - AUTH_TOKEN_GRPC_TLS_USER_CERT_FILE=/certs/ca-cert.pem
      ## TOKEN AUTHENTICATION
      - AUTH_TOKEN_SECRET=12345678901234567890123456789012
      - AUTH_ACCESS_TOKEN_DURATION=10h
      - AUTH_REFRESH_TOKEN_DURATION=24h
      - AUTH_USER_SESSION_DURATION=24h
      ## DATABASE
      - AUTH_CACHE_URL=redis://cache:6379/0
      - AUTH_DATABASE_MIGRATION_PATH=file://auth/internal/adapters/db/postgres/migrations
      - AUTH_DATABASE_URL=postgresql://postgres:postgres@db:5432/fingo_auth?sslmode=disable
      ## RABBITMQ
      - AUTH_RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - AUTH_RABBITMQ_NEW_SIGNIN_SESSION_QUEUE_NAME=new_signin_session
    ports:
      - "9002:9002"
    depends_on:
      - cache
      - db
      - rabbitmq
      - token
      - jaeger

  wallet:
    image: dekuyo/fingo_wallet:latest
    environment:
      - WALLET_GRPC_PORT=9003
      - TOKEN_GRPC_URL=token:9001
      ## TRACING
      - WALLET_TRACING_ENABLE=true
      - WALLET_TRACING_JAEGER_ENABLE=true
      - WALLET_TRACING_JAEGER_AGENT_URL=http://jaeger:14268/api/traces
      - WALLET_TRACING_JAEGER_SERVICE_NAME=wallet
      - WALLET_TRACING_JAEGER_ENVIRONMENT=development
      ## TLS CERTIFICATES
      - WALLET_GRPC_TLS_ENABLE=true
      - WALLET_GRPC_TLS_KEY_FILE=/certs/server-key.pem
      - WALLET_GRPC_TLS_CERT_FILE=/certs/server-cert.pem
      - WALLET_TOKEN_GRPC_TLS_USER_CERT_FILE=/certs/ca-cert.pem
      ## DATABASE
      - WALLET_DATABASE_URL=postgresql://root@crdb:26257/fingo_wallet?sslmode=disable
      - WALLET_DATABASE_MIGRATION_PATH=file://wallet/internal/adapters/db/sql/migrations
      ## CARD NUMBER GENERATOR
      - WALLET_CARD_NUMBER_LENGTH=16
      ## LOCKER
      - WALLET_LOCKER_CLEANUP_DURATION=1m
    ports:
      - "9003:9003"
    depends_on:
      - token
      - crdb

  token:
    image: dekuyo/fingo_token:latest
    environment:
      - TOKEN_GRPC_PORT=9001
      ## TRACING
      - TOKEN_TRACING_ENABLE=true
      - TOKEN_TRACING_JAEGER_ENABLE=true
      - TOKEN_TRACING_JAEGER_AGENT_URL=http://jaeger:14268/api/traces
      - TOKEN_TRACING_JAEGER_SERVICE_NAME=token
      - TOKEN_TRACING_JAEGER_ENVIRONMENT=development
      ## DATABASE
      - TOKEN_REDIS_URL=redis://cache:6379/0
      ## TLS CERTIFICATES
      - TOKEN_GRPC_TLS_ENABLE=true
      - TOKEN_GRPC_TLS_CERT_FILE=/certs/server-cert.pem
      - TOKEN_GRPC_TLS_KEY_FILE=/certs/server-key.pem
    ports:
      - "9001:9001"
    depends_on:
      - cache
      - jaeger

  contact:
    image: dekuyo/fingo_contact:latest
    environment:
      - CONTACT_CODES_EXPIRATION=30m
      - CONTACT_SEND_CODE_MIN_INTERVAL=2m
      - CONTACT_SEND_RESET_PASSWORD_TOKEN_MIN_INTERVAL=2m
      ## TRACING
      - CONTACT_TRACING_ENABLE=true
      - CONTACT_TRACING_JAEGER_ENABLE=true
      - CONTACT_TRACING_JAEGER_AGENT_URL=http://jaeger:14268/api/traces
      - CONTACT_TRACING_JAEGER_SERVICE_NAME=contact
      - CONTACT_TRACING_JAEGER_ENVIRONMENT=development
      ## RABBITMQ
      - CONTACT_RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - CONTACT_RABBITMQ_VERIFICATION_CODE_QUEUE_NAME=email_verification_code
      - CONTACT_RABBITMQ_RESET_PASSWORD_TOKEN_QUEUE_NAME=reset_password_token
      - CONTACT_RABBITMQ_NEW_SIGNIN_SESSION_QUEUE_NAME=new_signin_session
      ## COURIER
      - CONTACT_COURIER_TOKEN=dk_prod_B9AEG73NM9MPKTPBST17C05Q20JN
      - CONTACT_COURIER_VERIFICATION_TEMPLATE_ID=ACR2RAD0S04MX6QCMEKPB5VMR7D9
      - CONTACT_COURIER_RESET_PASSWORD_TEMPLATE_ID=VZA6RF7BJHMQJBGY0Q9VZR9RY5PS
      - CONTACT_COURIER_NEW_SIGNIN_SESSION_TEMPLATE_ID=NYT43T6ABS4XXDP5J9EH57J1V3BD
    depends_on:
      - rabbitmq
      - jaeger

  cache:
    image: redis:alpine
    volumes:
      - cache:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 5

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=fingo_auth
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./scripts/multiple-database.sh:/docker-entrypoint-initdb.d/multiple-database.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 5

  crdb: # Master node
    image: cockroachdb/cockroach:latest
    volumes:
      - crdb:/cockroach/cockroach-data
      - ./scripts/cockroach-inti.sh:/cockroach-inti.sh
    entrypoint: ["/bin/bash"]
    command: ["/cockroach-inti.sh"]
    ports:
      - "26257:26257"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "cockroach", "node", "status", "--insecure"]
      interval: 2s
      timeout: 2s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.10.19-management
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia/'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 3s
      timeout: 5s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:1.6
    ports:
      - "16686:16686"
      - "14268:14268"
      - "4318:4318"
      - "6831:6831/udp"

volumes:
  crdb:
  rabbitmq:
  cache:
  db:
