// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: currency.sql

package sqlc

import (
	"context"
)

const getCurrencyByID = `-- name: GetCurrencyByID :one
SELECT id, name
FROM currency
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCurrencyByID(ctx context.Context, db DBTX, id int16) (Currency, error) {
	row := db.QueryRowContext(ctx, getCurrencyByID, id)
	var i Currency
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getCurrencyByName = `-- name: GetCurrencyByName :one
SELECT id
FROM currency
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetCurrencyByName(ctx context.Context, db DBTX, name string) (int16, error) {
	row := db.QueryRowContext(ctx, getCurrencyByName, name)
	var id int16
	err := row.Scan(&id)
	return id, err
}
