// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Session struct {
	ID           uuid.UUID      `db:"id" json:"id"`
	UserID       uuid.UUID      `db:"user_id" json:"user_id"`
	RefreshToken string         `db:"refresh_token" json:"refresh_token"`
	IsBlocked    bool           `db:"is_blocked" json:"is_blocked"`
	UserAgent    sql.NullString `db:"user_agent" json:"user_agent"`
	ClientIp     sql.NullString `db:"client_ip" json:"client_ip"`
	ExpiresAt    time.Time      `db:"expires_at" json:"expires_at"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
}

type User struct {
	ID             uuid.UUID `db:"id" json:"id"`
	Name           string    `db:"name" json:"name"`
	Username       string    `db:"username" json:"username"`
	Email          string    `db:"email" json:"email"`
	HashedPassword string    `db:"hashed_password" json:"hashed_password"`
	IsVerified     bool      `db:"is_verified" json:"is_verified"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
}
