// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Role struct {
	ID   int32  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

type Session struct {
	ID           uuid.UUID `db:"id" json:"id"`
	UserID       uuid.UUID `db:"user_id" json:"user_id"`
	RefreshToken string    `db:"refresh_token" json:"refresh_token"`
	IsBlocked    bool      `db:"is_blocked" json:"is_blocked"`
	UserAgent    string    `db:"user_agent" json:"user_agent"`
	ClientIp     string    `db:"client_ip" json:"client_ip"`
	ExpiresAt    time.Time `db:"expires_at" json:"expires_at"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
}

type User struct {
	ID                uuid.UUID   `db:"id" json:"id"`
	FirstName         string      `db:"first_name" json:"first_name"`
	LastName          string      `db:"last_name" json:"last_name"`
	Username          string      `db:"username" json:"username"`
	Gender            interface{} `db:"gender" json:"gender"`
	Email             string      `db:"email" json:"email"`
	PhoneNumber       string      `db:"phone_number" json:"phone_number"`
	HashedPassword    string      `db:"hashed_password" json:"hashed_password"`
	PasswordChangedAt time.Time   `db:"password_changed_at" json:"password_changed_at"`
	IsVerifiedEmail   bool        `db:"is_verified_email" json:"is_verified_email"`
	IsVerifiedPhone   bool        `db:"is_verified_phone" json:"is_verified_phone"`
	Birthday          time.Time   `db:"birthday" json:"birthday"`
	CreatedAt         time.Time   `db:"created_at" json:"created_at"`
}

type UserRole struct {
	ID        int32     `db:"id" json:"id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	RoleID    int32     `db:"role_id" json:"role_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}
