// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteSessionByID(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteUserByID(ctx context.Context, id uuid.UUID) (int64, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserDevices(ctx context.Context, userID uuid.UUID) ([]GetUserDevicesRow, error)
	GetUserSessions(ctx context.Context, userID uuid.UUID) ([]Session, error)
	UpdateSessionTokens(ctx context.Context, arg UpdateSessionTokensParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
