name: deploy

on:
  push:
    branches:
      - "main"
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build and push (fingo_token)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./_deployments/Dockerfile.token
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fingo_token:latest

      - name: Build and push (fingo_auth)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./_deployments/Dockerfile.auth
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fingo_auth:latest

      - name: Build and push (fingo_wallet)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./_deployments/Dockerfile.wallet
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fingo_wallet:latest

      - name: Build and push (fingo_contact)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./_deployments/Dockerfile.contact
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fingo_contact:latest
