name: deploy

on:
  push:
    branches:
      - "main"
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Prepare to build for (fingo-token)
        run: cp ./token/.env.example ./token/app.env
      - name: Build and push (fingo-token)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./_deployments/Dockerfile.token
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fingo-token:latest

      - name: Prepare to build for (fingo-auth)
        run: cp ./auth/.env.example ./auth/app.env
      - name: Build and push (fingo-auth)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./_deployments/Dockerfile.auth
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fingo-auth:latest

      - name: Prepare to build for (fingo-wallet)
        run: cp ./wallet/.env.example ./wallet/app.env
      - name: Build and push (fingo-wallet)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./_deployments/Dockerfile.wallet
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fingo-wallet:latest

      - name: Prepare to build for (fingo-contact)
        run: cp ./contact/.env.example ./contact/app.env
      - name: Build and push (fingo-contact)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./_deployments/Dockerfile.contact
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fingo-contact:latest
